# Generated by Django 4.2.7 on 2023-11-02 16:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cctv",
            fields=[
                ("cctv_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "recent_image",
                    models.ImageField(
                        upload_to="cctv_images/<django.db.models.fields.BigIntegerField>/"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "created_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            11,
                            2,
                            16,
                            53,
                            59,
                            440296,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "alert_image",
                    models.ImageField(
                        upload_to="alert_images/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d"
                    ),
                ),
                (
                    "cctv_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cctv.cctv"
                    ),
                ),
            ],
        ),
    ]
