# Generated by Django 5.0 on 2023-12-12 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 12, 8, 53, 15, 927693, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
