# Generated by Django 4.2.7 on 2023-11-02 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0002_alter_alert_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 2, 17, 21, 28, 912467, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cctv",
            name="cctv_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cctv",
            name="recent_image",
            field=models.ImageField(
                upload_to="cctv_images/<django.db.models.fields.BigAutoField>/"
            ),
        ),
    ]
