# Generated by Django 5.0 on 2023-12-15 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0002_alter_alert_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 15, 11, 14, 44, 447777, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
