# Generated by Django 4.2.7 on 2023-11-02 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0003_alter_alert_created_date_alter_cctv_cctv_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="alert",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 2, 17, 22, 11, 683494, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
