# Generated by Django 5.0 on 2023-12-17 11:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0004_alter_alert_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="cctv_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cctv",
                to="cctv.cctv",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 17, 11, 31, 22, 665369, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
