# Generated by Django 5.0 on 2023-12-17 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0005_alter_alert_cctv_id_alter_alert_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 17, 11, 32, 5, 987730, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cctv",
            name="recent_image",
            field=models.ImageField(null=True, upload_to="cctv_images/"),
        ),
    ]
