# Generated by Django 5.0 on 2023-12-19 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cctv", "0006_alter_alert_created_date_alter_cctv_recent_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 19, 12, 20, 42, 964922, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
