# Generated by Django 5.0 on 2023-12-15 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                ("token_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.TextField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
